baseURL = "https://michaelbrunger.com/"   # Your site's URL (with trailing slash)
languageCode = "en-GB"
title = "Michael Brunger"                 # Site title
theme = ["github.com/adityatelange/hugo-PaperMod"]
pagerSize = 10                            # Posts per page

[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"

# Content settings
enableRobotsTXT = true                    # Generate robots.txt
buildDrafts = false                       # Set to true to build draft content
buildFuture = false                       # Set to true to build future dated content
enableEmoji = true                        # Enable emoji support in content
enableGitInfo = true                      # Use Git commit dates for content

# URL settings
canonifyURLs = true                       # Convert all URLs to absolute
relativeURLs = false                      # Use relative URLs

# Taxonomies (categories, tags, etc)
[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

# Author information
[author]
  name = "Michael Brunger"
  email = "michaelbrunger@gmail.com"

# Menu configuration
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 20

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 30

  [[menu.main]]
    identifier = "links"
    name = "Links"
    url = "/links/"
    weight = 40

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 50

# Theme-specific parameters
[params]
  # Basic site parameters
  description = "Michael Brunger's website"
  keywords = ["keyword1", "keyword2", "keyword3"]
  author = "Michael Brunger"
  images = ["site-feature-image.jpg"]
  DateFormat = "January 2, 2006"
  defaultTheme = "dark"  # Options: light, dark, auto
  disableThemeToggle = true
  env = "production"     # Options: production, development
  customCSS = ["css/custom.css"]
  accentColor = "emerald"
  homeLayout   = "cards"  # "cards", "list", or "minimal"
  cardsColumns = 3
  # PaperMod specific options
  showReadingTime      = true
  showShareButtons     = true
  showPostNavLinks     = true
  showBreadCrumbs      = false
  showCodeCopyButtons  = true
  showFullTextInRSS    = true
  showToc              = true

# Fonts (Google Fonts will be auto‐injected)
[params.fonts]
  body    = ["Inter", "sans-serif"]
  heading = ["Merriweather", "serif"]
  mono    = ["Fira Code", "monospace"]
  
# Social media links
[params.social]
    github = "https://github.com/michaelbZA"
    linkedin = "https://linkedin.com/in/michael-brunger"
    
# Analytics
[params.analytics.google]
  SiteVerificationTag = "G-XXXXXXXX"
[params.analytics.bing]
  SiteVerificationTag = "B-XXXXXXXX"
[params.analytics.yandex]
  SiteVerificationTag = "Y-XXXXXXXX"

    
  # Home page settings
  [params.homeInfoParams]
    Title = "Welcome to my digital garden"
    Content = "I'm a chartered accountant and finance manager documenting my learning journey. This site covers my explorations in Python programming, finance insights, parenting experiences, and philosophical musings."
    
  # Cover image for posts
  [params.cover]
    linkFullImages = true
    
  # Search functionality
  [params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    location = 0
    distance = 1000
    threshold = 0.4
    minMatchCharLength = 0
    keys = ["title", "permalink", "summary", "content"]

  # Favicon and icons
  [params.assets]
  favicon          = "/assets/favicon.ico"
  favicon16x16     = "/assets/favicon-16x16.png"
  favicon32x32     = "/assets/favicon-32x32.png"
  apple_touch_icon = "/assets/apple-touch-icon.png"
  safari_pinned_tab= "/assets/safari-pinned-tab.svg"

# Privacy settings
[privacy]
  [privacy.x]
    enableDNT = true
    simple    = true

#Render settings
[markup.goldmark.renderer]
  unsafe = true