[build]
  publish = "public"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.146.7"  # Replace with your Hugo version
  GO_VERSION = "1.22"

[context.production.environment]
  HUGO_ENV = "production"