name: Generate Daily News Brief

on:
  schedule:
    # Runs at 7 AM UTC (8 AM UK time in winter, 7 AM UK time in summer)
    - cron: '0 7 * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  generate-brief:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # Increased timeout for network operations
    
    permissions:
      contents: write # Explicitly grant write permissions
      issues: write  # For creating issues on failure
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0 # Ensure full history for git operations
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Create package.json if not exists
      run: |
        if [ ! -f package.json ]; then
          npm init -y
        fi
    
    - name: Install dependencies
      run: |
        npm install rss-parser axios date-fns dotenv
    
    - name: Generate news brief
      env:
        XAI_API_KEY: ${{ secrets.XAI_API_KEY }}
        NODE_TLS_REJECT_UNAUTHORIZED: '0'  # Add this if there are SSL issues
      run: node scripts/generate-brief.js
    
    - name: Debug - Check if files were created
      run: |
        echo "Checking if brief files were created..."
        ls -la content/briefs/ || echo "Briefs directory doesn't exist"
        find . -name "*.md" -newer /tmp -type f 2>/dev/null || echo "No recent .md files found"
    
    - name: Configure git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    
    - name: Commit and push if changed
      run: |
        git add content/briefs/
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "📰 Daily news brief - $(date +'%Y-%m-%d')"
          git push
        fi
    
    - name: Create issue on failure
      if: failure()
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: `Daily Brief Generation Failed - ${new Date().toISOString().split('T')[0]}`,
            body: `The daily news brief generation failed. Please check the workflow logs for details.
            
            Common issues to check:
            - Network connectivity to RSS feeds
            - XAI API key validity
            - File system permissions
            - RSS feed availability`
          })