name: Generate Daily News Brief

on:
  schedule:
    # Runs at 7 AM UTC (8 AM UK time in winter, 7 AM UK time in summer)
    - cron: '0 7 * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  generate-brief:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write # Explicitly grant write permissions
      issues: write  # For creating issues on failure
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0 # Ensure full history for git operations
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Create package.json if not exists
      run: |
        if [ ! -f package.json ]; then
          npm init -y
        fi
    
    - name: Install dependencies
      run: |
        npm install rss-parser axios date-fns dotenv
    
    - name: Generate news brief
      env:
        XAI_API_KEY: ${{ secrets.XAI_API_KEY }}
      run: node scripts/generate-brief.js
    
    - name: Check for changes
      id: verify-changed-files
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Commit and push changes
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        echo "Configuring git..."
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        
        echo "Adding files..."
        git add content/briefs/
        
        echo "Committing changes..."
        git commit -m "📰 Daily news brief - $(date +'%Y-%m-%d')" || exit 1
        
        echo "Pulling latest changes..."
        git pull --rebase || exit 1
        
        echo "Pushing changes..."
        git push || exit 1
        
        echo "Changes pushed successfully!"
    
    - name: Create issue on failure
      if: failure()
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: `Daily Brief Generation Failed - ${new Date().toISOString().split('T')[0]}`,
            body: `The daily news brief generation failed. Please check the workflow logs.`
          })