name: Generate Daily News Brief

on:
  schedule:
    # Runs at 7 AM UTC (8 AM UK time in winter, 7 AM UK time in summer)
    - cron: '0 7 * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  generate-brief:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Add timeout for the entire job
    
    permissions:
      contents: write # Explicitly grant write permissions
      issues: write  # For creating issues on failure
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0 # Ensure full history for git operations
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Create package.json if not exists
      run: |
        if [ ! -f package.json ]; then
          npm init -y
        fi
    
    - name: Install dependencies
      run: |
        npm install rss-parser axios date-fns dotenv
    
    - name: Generate news brief
      env:
        XAI_API_KEY: ${{ secrets.XAI_API_KEY }}
      run: node scripts/generate-brief.js
    
    - name: Commit and push if changed
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "📰 Daily news brief - $(date +'%Y-%m-%d')"
        file_pattern: content/briefs/
        branch: ${{ github.ref }}
    
    - name: Create issue on failure
      if: failure()
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: `Daily Brief Generation Failed - ${new Date().toISOString().split('T')[0]}`,
            body: `The daily news brief generation failed. Please check the workflow logs.`
          })